# Generated by Django 4.1.4 on 2022-12-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productgallery_options_alter_product_id_and_more'),
        ('carts', '0002_alter_cart_id_alter_cartitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(to='store.variation'),
        ),
    ]
